# Generated by Django 4.2.2 on 2023-07-09 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(choices=[('computer_engineering', 'Ingenieria En Computacion'), ('systems_engineering', 'Ingenieria De Sistemas'), ('electrical_engineering', 'Ingenieria Electrica'), ('petroleum_engineering', 'Ingeniería De Petróleo'), ('industrial_engineering', 'Ingeniería Industrial'), ('civil_engineering', 'Ingeniería Civil'), ('mechanical_engineering', 'Ingeniería Mecánica'), ('chemical_engineering', 'Ingeniería Química'), ('architecture', 'Arquitectura'), ('medicine', 'Medicina'), ('accounting', 'Contaduría'), ('business_administration', 'Administración')], max_length=32)),
                ('region', models.CharField(choices=[('AM', 'Amazonas'), ('AN', 'Anzoátegui'), ('AP', 'Apure'), ('AR', 'Aragua'), ('BA', 'Barinas'), ('BO', 'Bolívar'), ('CA', 'Carabobo'), ('CO', 'Cojedes'), ('DE', 'Delta Amacuro'), ('DC', 'Distrito Capital'), ('FA', 'Falcón'), ('GU', 'Guárico'), ('LA', 'Lara'), ('ME', 'Mérida'), ('MI', 'Miranda'), ('MO', 'Monagas'), ('NE', 'Nueva Esparta'), ('PR', 'Portuguesa'), ('SU', 'Sucre'), ('TA', 'Táchira'), ('TR', 'Trujillo'), ('VA', 'Vargas'), ('YA', 'Yaracuy'), ('ZU', 'Zulia')], max_length=32)),
                ('national_id_prefix', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], max_length=1)),
                ('national_id_number', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
