# Generated by Django 4.2.2 on 2023-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.IntegerField(),
        ),
    ]
