# Generated by Django 4.2.2 on 2023-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_course_alter_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.IntegerField(default=0),
        ),
    ]
