# Generated by Django 4.2.2 on 2023-07-30 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('grades', '0002_grade_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
