# Generated by Django 4.2.2 on 2023-07-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_grade_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='course',
            new_name='courseId',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='student',
            new_name='studentId',
        ),
    ]
