# Generated by Django 4.2.2 on 2023-07-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_rename_course_grade_courseid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='courseId',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='studentId',
            new_name='student_id',
        ),
    ]
