# Generated by Django 4.2.2 on 2023-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_alter_subject_career_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
