# Generated by Django 4.2.2 on 2023-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_alter_subject_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='career',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
