# Generated by Django 4.2.2 on 2023-07-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_remove_career_id_alter_career_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
