# Generated by Django 4.2.2 on 2023-07-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_career_id_alter_career_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
