# Generated by Django 4.2.2 on 2023-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0012_alter_career_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='career',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
