# Generated by Django 4.2.2 on 2023-07-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='enrollment',
            new_name='user',
        ),
    ]
