# Generated by Django 4.2.2 on 2023-07-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_enrollment_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=128),
        ),
    ]
