# Generated by Django 4.2.2 on 2023-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
